locations = ['Arizona', 'Moon', 'Australia', 'Hogwarts', 'Iceland']
print(locations)
print(sorted(locations))
locations.reverse()
print(locations)
locations.reverse()
print(locations)
locations.sort()
print(locations)
locations.reverse()
print(locations)
print(len(locations))